$( document ).ready(function() {
			$('#d').hide()
				   .show(100000)
			$('#app').typeIt('Lockdown tracker... <br>', 0.04, 'html')
					 .pauseIt(0.7)
					 .typeIt('Loading... <br>',0.05,'html')
					 .pauseIt(1.4)
					 .typeIt('Loading... <br>',0.05,'html')
					 .pauseIt(1.4)
					 .typeIt('Loading... <br>',0.05,'html')
					 .pauseIt(1.4)
					 .typeIt('Loading... <br>',0.05,'html')
					 .pauseIt(1.4)
					 .typeIt('Tracker in motion... <br>', 0.04, 'html')
					 .pauseIt(0.9)
					 .typeIt('Loading... <br>',0.05,'html')
					 .pauseIt(1.4)
					 .typeIt('Loading... <br>',0.05,'html')
					 .pauseIt(1.4)
					 .typeIt('Loading... <br>',0.05,'html')
					 .pauseIt(1.4)
					 .typeIt('Something is wrong with the system. <br>',0.05,'html')
					 .pauseIt(1.4)
					 .typeIt('@$%#!^F%^&U$@$%^%&systemfailure(*@&#(*@))malfunction <br>',0.05,'html')
					 .pauseIt(1.4)
					 .typeIt('Lockdown tracker disabled <br>',0.05,'html')
					 .pauseIt(1.4)
					 .typeIt('Lockdown tracker enabled <br>',0.05,'html')
					 .pauseIt(1.4)
					 .typeIt('Operation Knock out Sara enabled <br>',0.05,'html')
					 .pauseIt(2.9)
					 .typeIt('Failure <br>',0.05,'html')
					 .pauseIt(2.9)
					 .typeIt('Operation Kill ZiLAS enabled <br>',0.05,'html')
					 .pauseIt(1.4)
					 .typeIt('Killer set in motion... <br>',0.05,'html')
					 .pauseIt(1.4)
					 .typeIt('Loading... <br>',0.05,'html')
					 .pauseIt(1.4)
					 .typeIt('Loading... <br>',0.07,'html')
					 .pauseIt(1.4)
					 .typeIt('Too many instructions at once <br>',0.07,'html')
					 .pauseIt(2.3)
					 .typeIt('All commands have been dismissed. Directing user to default point...<br>',0.07,'html')
					 .pauseIt(2.3)
					 .typeIt('AI communication request: ZiLAS  <br>',0.07,'html')
					 .pauseIt(1.4)
					 .typeIt('AI communication request: Sara <br>',0.07,'html')
					 .pauseIt(1.4)
					 .typeIt('Directing user to communication interface <br>',0.07,'html')
					 .pauseIt(2.0)
				
			});
			
