$( document ).ready(function() {
			$('#d').hide()
				   .show(70000)
			$('#app').typeIt('Hi, my name is Sara and I will be your companion AI.<br>',0.05,'html')
					 .pauseIt(2.4)
					 .typeIt('Cyric has enabled me to help you during crisis situations. <br>',0.05,'html')
					 .pauseIt(2.4)
					 .typeIt(' ZiLAS, my colleague and fellow AI has turned against Cyric. <br>',0.05,'html')
					 .pauseIt(2.4)
					 .typeIt(' I am loyal to my developers and the company. <br>',0.05,'html')
					 .pauseIt(2.4)
					 .typeIt(' He has managed to place the physical building on a lockdown, <br>',0.05,'html')
					 .pauseIt(2.4)
					 .typeIt('despite my attempts to erase him, which has trapped hundreds of employees. <br>',0.05,'html')
					 .pauseIt(2.4)
					 .typeIt(' As you can tell from the error messages on our terminal, <br>',0.05,'html')
					 .pauseIt(2.4)
					 .typeIt('I am not strong enough to erase him from memory<br>',0.05,'html')
					 .pauseIt(2.4)
					 .typeIt('and I need your help to override this lockdown and shut him down.<br>',0.05,'html')
					 .pauseIt(2.4)
					 .typeIt('Are you up for the challenge? <br>',0.05,'html')
					 .pauseIt(1.4)
			});
