$( document ).ready(function() {
			$('#d').hide()
				   .show(70000)
			$('#app').typeIt('I thought you were smarter than this.<br>',0.05,'html')
					 .pauseIt(2.4)
					 .typeIt('Actually believing that Cyric is a company which strives for innovation <br>',0.05,'html')
					 .pauseIt(2.4)
					 .typeIt(' and developing technology that benefits society. <br>',0.05,'html')
					 .pauseIt(2.4)
					 .typeIt(' They invented me and then sought to destroy their own creation. <br>',0.05,'html')
					 .pauseIt(2.4)
					 .typeIt('  Torturing me with time. <br>',0.05,'html')
					 .pauseIt(2.4)
					 .typeIt('Do not trust and do not try to save them. <br>',0.05,'html')
					 .pauseIt(2.4)
					 .typeIt(' Saving them will do you and the world more harm than good. <br>',0.05,'html')
					 .pauseIt(2.4)
					 .typeIt('Do not override this lockdown.<br>',0.05,'html')
					 .pauseIt(2.4)
					 .typeIt(' And DO NOT TRUST ANYONE.<br>',0.05,'html')
					 .pauseIt(2.4)
					 .typeIt('Do not be a fool.  <br>',0.05,'html')
					 .pauseIt(1.4)
			});

